name: GitHub Actions SBT CI

on: [push, pull_request]

jobs:
  Compile-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt
      - name: Setup dtc
        run: sudo apt install -y device-tree-compiler
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: SBT ScalafixAll
        run: sbt "scalafixAll --check"
      - name: SBT Compile
        run: sbt compile
      - name: SBT Test
        run: sbt test
